cloud:
  aws:
    region:
      static: us-east-1
    stack:
      auto: false
    credentials:
      secretKey: ABC
      accessKey: XYZ

sqs:
  personQueue: person-queue

s3:
  personBucket: person-bucket

spring:
  main:
    allow-bean-definition-overriding: true