cloud:
  aws:
    region:
      static: us-east-1
    stack:
      auto: false
    credentials:
      secretKey: test
      accessKey: test
    sqs:
      enabled: true
      region: us-east-1
      endpoint: http://localhost:4566
sqs:
  personQueue: person-queue

s3:
  personBucket: person-bucket

spring:
  main:
    allow-bean-definition-overriding: true

